# Generated by Django 5.2.4 on 2025-08-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booktracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="\\covers", verbose_name="Обложка"
            ),
        ),
    ]
