# Generated by Django 5.2.4 on 2025-07-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booktracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="genre_id",
            new_name="genre",
        ),
    ]
