
services:
  db:
    image: postgres:15
    container_name: postgres_booktracker
    environment:
      POSTGRES_DB: booktracker
      POSTGRES_USER: kirill
      POSTGRES_PASSWORD: password
    ports:
      - "5472:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
